plants:
    - {"color": [0, 255, 0], "power": 30, "life": 50, "range": 400, "price": 50}
    - {"color": [0, 196, 0], "power": 40, "life": 50, "range": 400, "price": 80}
    - {"color": [0, 128, 0], "power": 60, "life": 50, "range": 400, "price": 120}